FROM nvcr.io/nvidia/pytorch:20.12-py3

# Install linux packages
RUN echo "nameserver 10.1.1.50" | tee /etc/resolv.conf > /dev/null
RUN apt-get update ##[edited]
RUN apt-get install -y screen libgl1-mesa-glx
# Install python dependencies
RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install gsutil

ENV PATH=$PATH:/home/asandygulova/dock/SCTK/src/sclite

ENV PATH=$PATH:/home/asandygulova/dock/torchzq

RUN echo $PATH

COPY . /home/asandygulova/dock

WORKDIR /home/asandygulova/dock
